### ISSUE TITLE
Offsets at Graphics Settings

### ISSUE THREAD

**Issue by brunofporto** [simcodersdotcom/headshake#13]
When I have HeadShake installed, sometimes and I was not able to reproduce it, it appears small values at the Roll Offset setting at the Graphic Settings of X-plane.

I tried different situations (pause, close x-plane, alt+f4, change plane, new flight, etc) but was not able to reproduce it yet. But it does not happens when I have HeadShake disabled. 

ps.: Just realized that I did not test to disable HeadShake during some manouver to check it.

**Comment by nico87** [comment]
Usually this happens if you crash the plane. We should put a sort of check to reset the view after a crash.

**Comment by brunofporto** [comment]
I'll try it! Thank you. For now at least I know when to check for the offset.

ps.: Do I keep this issue as open?
