### ISSUE TITLE
Sound on startup: "Headshake is enabled"

### ISSUE THREAD

**Issue by tameraktasTU** [simcodersdotcom/headshake#18]
The sound "Headshake is enabled" is played on every XPlane 11 start, is there a possibility to remove the sound in settings or even coompletly?

**Comment by nico87** [comment]
@abdullah-radwan could this be related to https://github.com/simcodersdotcom/headshake/pull/16 ?

**Comment by abdullah-radwan** [comment]
Yes. It's XPLMSpeakString.

**Comment by nico87** [comment]
I see. That's why I saw the message only. I'm on Linux!
I prefer to have it disabled. I already made the change with https://github.com/simcodersdotcom/headshake/commit/99d15bb54cb685367889e9a110770548c6d074a4
