### ISSUE TITLE
Possible bug in gforcecameracommand.cpp

### ISSUE THREAD

**Issue by quantumac** [simcodersdotcom/headshake#19]
Line 142 of gforcecameracommand.cpp reads "if (acc < 0.005 || acc > 0.005)".  Shouldn't it be instead "if (acc < -0.005 || acc > 0.005)".  In other words, this line and the following statements is trying to say "if the value is +/- close to zero, make it zero, otherwise use the value."  The current code only zeros if the value is equal to precisely positive 0.005.

**Comment by nico87** [comment]
That's definitely a typo!
Fixed with 1e87df5a6863a3e461e25c8b30462d22a9d1af34

Thanks
