### ISSUE TITLE
Binary for ARM Macs

### ISSUE THREAD

**Issue by wooter** [simcodersdotcom/headshake#33]
Just to let you know the release is missing an ARM compatible Mac.xpl.

I managed to compile mine with the instructions provided, so it's not a big deal if you're kind of handy, but it would be more convenient to have an updated Mac.xpl if you're not so developer inclined.

**Comment by nico87** [comment]
Thank you! It would be cool if you make a pull request with an updated CmakesLists.txt.

**Comment by nico87** [comment]
ARM CPU support added with 4478d2845102ad77049b2ac4de0a879bd73befac
