### ISSUE TITLE
Taxi lookahead

### ISSUE THREAD

**Issue by nico87** [simcodersdotcom/headshake#5]
While taxiing, the view should move towars the turn direction.
It should be possible to activate/deactivate this option and also set its sensitivity.

**Comment by Althar93** [comment]
This task seems fairly trivial - it would probably make sense to have it part of/extend the "ground roll"? I would be more than happy to have a go implementing this if there are no other takers.

**Comment by nico87** [comment]
Hi!

I would keep this separated from the ground roll because, even tho they acts together, the two effects have different meanings to the user.
No problem if you want to take both issues! ;-)

**Comment by Althar93** [comment]
"I would keep this separated from the ground roll" - No problem I can keep them separate.

**Comment by Althar93** [comment]
While I have not had the time/chance to come up with a definite solution yet, I have been able to experiment with both passive (ie. G-force) and active (ie. monitor rudder input) lookahead. It feels like the best of both worlds could be a blend of the two (with the user being able to adjust their individual responses and mix). 

The final aspect that may require some thought is the transition/fade into a high speed/takeoff profile where looking straight ahead of the runway is probably more desirable than looking into the turn. Based on my early experiments, the taxi lookahead can actually be quite disorienting/overly sensitive at high speeds when the effect feels rather subtle at taxi speeds.

**Comment by nico87** [comment]
A blend may be perfect.
You can also reduce the sensitivity of the effect basing on the speed AND the throttle position, basing on, let's say, the maximum value of the two.
If I'm stopped on the runway with max throttle, I assume I'm going to takeoff.
